name: Deploy Personal Site to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: Build Go Binary
        run: go build -o main main.go

      - name: SCP Frontend to Production Server
        env:
          SSH_PASS: ${{ secrets.PRODUCTION_SERVER_PASS }}
        run: |
          sshpass -p "$SSH_PASS" scp -o StrictHostKeyChecking=no -r dist/* ${{ secrets.PRODUCTION_SERVER_USERNAME }}@${{ vars.PRODUCTION_SERVER_IP }}:/path/to/deployment/dist/

      - name: SCP Go Binary to Production Server
        env:
          SSH_PASS: ${{ secrets.PRODUCTION_SERVER_PASS }}
        run: |
          sshpass -p "$SSH_PASS" scp -o StrictHostKeyChecking=no main ${{ secrets.PRODUCTION_SERVER_USERNAME }}@${{ vars.PRODUCTION_SERVER_IP }}:/path/to/deployment/

      - name: Restart Server Service
        env:
          SSH_PASS: ${{ secrets.PRODUCTION_SERVER_PASS }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no ${{ secrets.PRODUCTION_SERVER_USERNAME }}@${{ vars.PRODUCTION_SERVER_IP }} "sudo systemctl restart personal-site.service"
